# Generated by Django 5.1.1 on 2024-09-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('image', models.ImageField(upload_to='team/', verbose_name='Фотография сотрудника')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описние')),
                ('rols', models.CharField(max_length=244, verbose_name='Должность')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Ссылка на instagram')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='Ссылка на linkedin')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Ссылка на facebook')),
            ],
            options={
                'verbose_name': 'Комманда',
                'verbose_name_plural': 'Комманды',
            },
        ),
    ]
