# Generated by Django 5.1.1 on 2024-09-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0003_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='partner/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Парнтер',
                'verbose_name_plural': 'Парнтеры',
            },
        ),
    ]
