# Generated by Django 5.1.1 on 2024-09-19 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0006_pricing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progres',
            options={'verbose_name': 'Прогрец', 'verbose_name_plural': 'Прогрецы'},
        ),
        migrations.CreateModel(
            name='PricingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('pricing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_service', to='secondary.pricing')),
            ],
            options={
                'verbose_name': 'Что входит в покет',
                'verbose_name_plural': 'Что входит в покет',
            },
        ),
    ]
