# Generated by Django 5.1.1 on 2024-09-19 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0008_teaminfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamInfoDop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_info_dop', to='secondary.team')),
            ],
        ),
    ]
