# Generated by Django 5.1.1 on 2024-09-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0009_teaminfodop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateField(auto_created=True, verbose_name='Дата'),
        ),
    ]
