# Generated by Django 5.1.1 on 2024-09-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0010_alter_news_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
