# Generated by Django 5.1.1 on 2024-09-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название сайта')),
                ('desc', models.TextField(verbose_name='Описание компании')),
                ('logo', models.ImageField(upload_to='logo/', verbose_name='Логотип сайта')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('schedul', models.CharField(max_length=255, verbose_name='График работы')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Ссылка на facebook')),
                ('linkendin', models.URLField(blank=True, null=True, verbose_name='Ссылка на linkendin')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Ссылка на instagram')),
                ('whatsapp', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер whatsapp')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
            },
        ),
    ]
