# Generated by Django 5.1.1 on 2024-09-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_slider_alter_setting_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='url',
            field=models.URLField(blank=True, help_text='Куда перейдет при нажати на кнопку', null=True, verbose_name='Ссылка'),
        ),
    ]
