# Generated by Django 5.1.1 on 2024-09-13 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_service', to='base.about', verbose_name='О нас')),
            ],
            options={
                'verbose_name': 'Услуги',
                'unique_together': {('about', 'title')},
            },
        ),
    ]
