# Generated by Django 5.1.1 on 2024-09-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_aboutservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='Видео'),
        ),
    ]
