# Generated by Django 5.1.1 on 2024-09-13 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_about_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutservice',
            options={'verbose_name': 'Услуги', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterUniqueTogether(
            name='aboutservice',
            unique_together=set(),
        ),
    ]
