# Generated by Django 5.1.1 on 2024-09-13 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_aboutservice_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_image', verbose_name='Фотография')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_image', to='base.about', verbose_name='О нас')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографи',
            },
        ),
    ]
