# Generated by Django 5.1.1 on 2024-09-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_aboutimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='Фото 1'),
        ),
        migrations.AddField(
            model_name='about',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='Фото 2'),
        ),
        migrations.AddField(
            model_name='about',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='Фото 3'),
        ),
        migrations.DeleteModel(
            name='AboutImage',
        ),
    ]
