# Generated by Django 5.1.1 on 2024-09-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_about_image_1_about_image_2_about_image_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='about/image', verbose_name='Фото 1'),
        ),
        migrations.AlterField(
            model_name='about',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='about/image', verbose_name='Фото 2'),
        ),
        migrations.AlterField(
            model_name='about',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='about/image', verbose_name='Фото 3'),
        ),
    ]
