# Generated by Django 5.1.1 on 2024-09-15 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_aboutstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutstate',
            name='icon',
            field=models.ImageField(default=1, upload_to='icon-state/', verbose_name='Иконки'),
            preserve_default=False,
        ),
    ]
