# Generated by Django 5.1.1 on 2024-09-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_aboutstate_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutstate',
            name='state',
            field=models.CharField(max_length=255, verbose_name='Цифра'),
        ),
    ]
