# Generated by Django 5.1.1 on 2024-09-15 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_aboutstate_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('number', models.CharField(max_length=255, verbose_name='Значение')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_skill', to='base.about', verbose_name='О нас')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
            },
        ),
    ]
