# Generated by Django 5.1.1 on 2024-09-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_aboutskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='choose_icon', verbose_name='Иконка')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Подзаголовок')),
            ],
            options={
                'verbose_name': 'Почему выберают нас',
                'verbose_name_plural': 'Почему выберают нас',
            },
        ),
    ]
