# Generated by Django 5.1.1 on 2024-09-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(verbose_name='Номер шага')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.ImageField(help_text='Загрузите иконку для этого шага процесса', upload_to='icons/', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Шаг рабочего процесса',
                'verbose_name_plural': 'Шаги рабочего процесса',
                'ordering': ['step_number'],
            },
        ),
    ]
