# Generated by Django 5.1.1 on 2024-09-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('icon', models.ImageField(upload_to='service_icon/', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': ('Услуга',),
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
