# Generated by Django 5.1.1 on 2024-09-15 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_service', to='project.service', verbose_name='Услуга'),
            preserve_default=False,
        ),
    ]
